"""Remove gender from product

Revision ID: 15379a08f0a4
Revises: ae84a4f38f2b
Create Date: 2025-12-22 18:53:33.354769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15379a08f0a4'
down_revision: Union[str, Sequence[str], None] = 'ae84a4f38f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'UNISEX', name='gender'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
